package SUNY_CSC_SCR::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'suny_csc_scr::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:aalot001',
        user => 'asing012_data',
        password => 'uAnTfo53NQ',
        AutoCommit => q{1},
    }
);

=head1 NAME

SUNY_CSC_SCR::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<SUNY_CSC_SCR>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<suny_csc_scr::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Ruslan Shakirov

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
